services:
  mariadb:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  api:
    build:
      context: ./tsapi
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8090:8090"
    restart: always

  # data-collector:
  #   build:
  #     context: ./data-collector
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - api
  #   environment:
  #     CHANNEL_ID1: ${THINGSPEAK_CHANNEL_ID1}
  #     CHANNEL_ID2: ${THINGSPEAK_CHANNEL_ID2}
  #   restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "8081:8080"
    volumes:
      - ./web:/usr/src/app   # 로컬 경로를 컨테이너 경로로 마운트
      - /usr/src/app/node_modules   # node_modules는 컨테이너 내부에만 존재하게 함
    restart: always

volumes:
  db_data: