version: '3.8'

services:
  mariadb:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: thingspeak_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  data-collector:
    build:
      context: ./data-collector
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: thingspeak_data
      CHANNEL_ID: ${CHANNEL_ID}
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "80:80"
    environment:
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: thingspeak_data
    restart: always

volumes:
  db_data:
